<?php
/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GeniusReferralsLib\Models;

use JsonSerializable;

/**
 * The advocate's form
 */
class AdvocateForm implements JsonSerializable
{
    /**
     * The advocate's wrapper
     * @required
     * @var Advocate $advocate public property
     */
    public $advocate;

    /**
     * Constructor to set initial or default values of member properties
     * @param Advocate $advocate Initialization value for $this->advocate
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->advocate = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['advocate'] = $this->advocate;

        return $json;
    }
}
