<?php
/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GeniusReferralsLib\Models;

use JsonSerializable;

/**
 * A bonus structure
 */
class Bonuses implements JsonSerializable
{
    /**
     * The referral's token. Usually the one that completed the purchase, or trigger an event.
     * @required
     * @maps advocate_token
     * @var string $advocateToken public property
     */
    public $advocateToken;

    /**
     * The reference number for this request. Usually the order_id, payment_id, or timestamp.
     * @required
     * @var string $reference public property
     */
    public $reference;

    /**
     * The payment amount the referrals has made. Required for a percentage based campaign.
     * @maps payment_amount
     * @var double $paymentAmount public property
     */
    public $paymentAmount;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $advocateToken Initialization value for $this->advocateToken
     * @param string $reference     Initialization value for $this->reference
     * @param double $paymentAmount Initialization value for $this->paymentAmount
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->advocateToken = func_get_arg(0);
            $this->reference     = func_get_arg(1);
            $this->paymentAmount = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['advocate_token'] = $this->advocateToken;
        $json['reference']      = $this->reference;
        $json['payment_amount'] = $this->paymentAmount;

        return $json;
    }
}
