<?php
/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GeniusReferralsLib\Models;

use JsonSerializable;

/**
 * The force bonuses' form
 */
class ForceBonusesForm implements JsonSerializable
{
    /**
     * The bonuses' wrapper
     * @required
     * @var ForceBonuses $bonus public property
     */
    public $bonus;

    /**
     * Constructor to set initial or default values of member properties
     * @param ForceBonuses $bonus Initialization value for $this->bonus
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->bonus = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['bonus'] = $this->bonus;

        return $json;
    }
}
