<?php
/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GeniusReferralsLib\Models;

use JsonSerializable;

/**
 * A bonus structure
 */
class ForceBonuses implements JsonSerializable
{
    /**
     * The referral's token.
     * @required
     * @maps advocate_token
     * @var string $advocateToken public property
     */
    public $advocateToken;

    /**
     * The reference number for this request. Usually the order_id, payment_id, or timestamp.
     * @required
     * @var string $reference public property
     */
    public $reference;

    /**
     * The bonus amount to give to the advocate.
     * @required
     * @maps bonus_amount
     * @var integer $bonusAmount public property
     */
    public $bonusAmount;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $advocateToken Initialization value for $this->advocateToken
     * @param string  $reference     Initialization value for $this->reference
     * @param integer $bonusAmount   Initialization value for $this->bonusAmount
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->advocateToken = func_get_arg(0);
            $this->reference     = func_get_arg(1);
            $this->bonusAmount   = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['advocate_token'] = $this->advocateToken;
        $json['reference']      = $this->reference;
        $json['bonus_amount']   = $this->bonusAmount;

        return $json;
    }
}
