<?php
/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GeniusReferralsLib\Models;

use JsonSerializable;

/**
 * The Payment Method Form
 */
class PaymentMethodForm implements JsonSerializable
{
    /**
     * The payment methods wrapper
     * @required
     * @maps advocate_payment_method
     * @var PaymentMethod $advocatePaymentMethod public property
     */
    public $advocatePaymentMethod;

    /**
     * Constructor to set initial or default values of member properties
     * @param PaymentMethod $advocatePaymentMethod Initialization value for $this->advocatePaymentMethod
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->advocatePaymentMethod = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['advocate_payment_method'] = $this->advocatePaymentMethod;

        return $json;
    }
}
