<?php
/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GeniusReferralsLib\Models;

use JsonSerializable;

/**
 * The payment method structure
 */
class PaymentMethod implements JsonSerializable
{
    /**
     * The username
     * @required
     * @var string $username public property
     */
    public $username;

    /**
     * The description
     * @required
     * @var string $description public property
     */
    public $description;

    /**
     * Is the payment method active? (true, false)
     * @required
     * @maps is_active
     * @var string $isActive public property
     */
    public $isActive;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $username    Initialization value for $this->username
     * @param string $description Initialization value for $this->description
     * @param string $isActive    Initialization value for $this->isActive
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->username    = func_get_arg(0);
            $this->description = func_get_arg(1);
            $this->isActive    = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['username']    = $this->username;
        $json['description'] = $this->description;
        $json['is_active']   = $this->isActive;

        return $json;
    }
}
