<?php
/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GeniusReferralsLib\Models;

use JsonSerializable;

/**
 * Redemption Request structure
 */
class RedemptionRequest implements JsonSerializable
{
    /**
     * The advocate's token
     * @required
     * @maps advocate_token
     * @var string $advocateToken public property
     */
    public $advocateToken;

    /**
     * The request status identifier
     * @required
     * @maps request_status_slug
     * @var string $requestStatusSlug public property
     */
    public $requestStatusSlug;

    /**
     * The request action identifier
     * @required
     * @maps request_action_slug
     * @var string $requestActionSlug public property
     */
    public $requestActionSlug;

    /**
     * The currency code
     * @required
     * @maps currency_code
     * @var string $currencyCode public property
     */
    public $currencyCode;

    /**
     * The amount to be redeemed
     * @required
     * @var integer $amount public property
     */
    public $amount;

    /**
     * The description of the requests, useful to store extra information about the request.
     * @var string $description public property
     */
    public $description;

    /**
     * The advocate's PayPal username
     * @maps advocates_paypal_username
     * @var string $advocatesPaypalUsername public property
     */
    public $advocatesPaypalUsername;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $advocateToken           Initialization value for $this->advocateToken
     * @param string  $requestStatusSlug       Initialization value for $this->requestStatusSlug
     * @param string  $requestActionSlug       Initialization value for $this->requestActionSlug
     * @param string  $currencyCode            Initialization value for $this->currencyCode
     * @param integer $amount                  Initialization value for $this->amount
     * @param string  $description             Initialization value for $this->description
     * @param string  $advocatesPaypalUsername Initialization value for $this->advocatesPaypalUsername
     */
    public function __construct()
    {
        if (7 == func_num_args()) {
            $this->advocateToken           = func_get_arg(0);
            $this->requestStatusSlug       = func_get_arg(1);
            $this->requestActionSlug       = func_get_arg(2);
            $this->currencyCode            = func_get_arg(3);
            $this->amount                  = func_get_arg(4);
            $this->description             = func_get_arg(5);
            $this->advocatesPaypalUsername = func_get_arg(6);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['advocate_token']            = $this->advocateToken;
        $json['request_status_slug']       = $this->requestStatusSlug;
        $json['request_action_slug']       = $this->requestActionSlug;
        $json['currency_code']             = $this->currencyCode;
        $json['amount']                    = $this->amount;
        $json['description']               = $this->description;
        $json['advocates_paypal_username'] = $this->advocatesPaypalUsername;

        return $json;
    }
}
