<?php
/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GeniusReferralsLib\Models;

use JsonSerializable;

/**
 * The referral structure
 */
class Referral implements JsonSerializable
{
    /**
     * The referrals token
     * @required
     * @maps referred_advocate_token
     * @var string $referredAdvocateToken public property
     */
    public $referredAdvocateToken;

    /**
     * The referral origin identifier
     * @required
     * @maps referral_origin_slug
     * @var string $referralOriginSlug public property
     */
    public $referralOriginSlug;

    /**
     * The campaign identifier
     * @required
     * @maps campaign_slug
     * @var string $campaignSlug public property
     */
    public $campaignSlug;

    /**
     * The http_referrer URL
     * @required
     * @maps http_referer
     * @var string $httpReferer public property
     */
    public $httpReferer;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $referredAdvocateToken Initialization value for $this->referredAdvocateToken
     * @param string $referralOriginSlug    Initialization value for $this->referralOriginSlug
     * @param string $campaignSlug          Initialization value for $this->campaignSlug
     * @param string $httpReferer           Initialization value for $this->httpReferer
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->referredAdvocateToken = func_get_arg(0);
            $this->referralOriginSlug    = func_get_arg(1);
            $this->campaignSlug          = func_get_arg(2);
            $this->httpReferer           = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['referred_advocate_token'] = $this->referredAdvocateToken;
        $json['referral_origin_slug']    = $this->referralOriginSlug;
        $json['campaign_slug']           = $this->campaignSlug;
        $json['http_referer']            = $this->httpReferer;

        return $json;
    }
}
