<?php
/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GeniusReferralsLib;

/**
 * All configuration including auth info and base URI for the API access
 * are configured in this class.
 */
class Configuration
{
    /**
     * The base Uri for API calls
     * @var string
     */
    public static $BASEURI = 'https://api.geniusreferrals.com';

    /**
     * The content type
     * @var string
     */
    /**
     * @todo Replace the $contentType with an appropriate value
     */
    public static $contentType = 'application/json';

    /**
     * Your API Token, you can get your token here https://www.geniusreferrals.com/en/settings/api-access
     * @var string
     */
    /**
     * @todo Replace the $xAuthToken with an appropriate value
     */
    public static $xAuthToken = '3b9d11374b602fb47b987dff90f1c5940a1f377f';
}
